# Puerto diferente para que corran juntos
server.port=${PORT:8081}

# Conexión a Supabase (PostgreSQL)
# URL construida desde tu captura (Transaction Pooler)
# Antes: spring.datasource.url=${SPRING_DB_URL}
spring.datasource.url=${DB_URL}

# Usuario exacto de tu imagen
spring.datasource.username=${DB_USERNAME}

# Tu contraseña
spring.datasource.password=${DB_PASSWORD}

# Configuraciones necesarias para Supabase Pooler
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true